server:
  port: 8080


plugin:
  runMode: dev
  enable: true
  pluginPath: /Users/chengen.gu/workspace/github/springboot-demo/plugin-framework-example/plugins
  sortInitPluginIds:
    - example-plugin12
    - example-plugin3
